app:
  name: ${name}
  version: ${version}


twitter:
  url: https://api.twitter.com/2/


spring:
  datasource:
    url: jdbc:postgresql://localhost:2777/postgres
    username: postgres
    password: postgres
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      enable_lazy_load_no_trans: true
    hibernate.ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          twitter:
            providerId: twitter
            clientId: dm91MTRyamwxTlV5RDg2X01IeTU6MTpjaQ
            clientSecret: Ulq5ZJuSQvFmRS7GKZQ25i7s9Ee9a0MPEoJkWyZvtMzEb6hQOD
            redirect-uri: http://localhost:8080/login/oauth2/code/twitter
            authorization-grant-type: authorization_code
            scope: [ tweet.read, users.read, offline.access, list.read ]
        provider:
          twitter:
            userInfoUri: https://api.twitter.com/2/users/me
            userNameAttribute: data
            token-uri: https://api.twitter.com/2/oauth2/token
            authorization-uri: https://twitter.com/i/oauth2/authorize